FROM node:20-alpine

RUN apk add --no-cache bash

WORKDIR /app

COPY infra/docker/.npmrc /root/.npmrc
COPY infra/docker/node-entrypoint.sh /docker-entrypoint/node-entrypoint.sh
RUN chmod +x /docker-entrypoint/node-entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["bash", "./entrypoint.sh"]
